
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author juliann
 */
public class FAsignaciones extends javax.swing.JFrame {

    ConexionHR cnx;
    String tabla = "asignaciones";

    public FAsignaciones(ConexionHR cnx) {
        initComponents();

        this.cnx = cnx;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Gestión de Asignaciones");

        cargarCombos();
        cargarDatos();
        generarGrafica();
    }

    private void cargarDatos() {
        String consulta = "SELECT a.id_asignacion, c.nombre_curso AS Curso, i.nombre_completo AS Instructor, "
                + "a.horario_especifico AS Horario, a.aula AS Aula, a.modalidad AS Modalidad "
                + "FROM asignaciones a "
                + "INNER JOIN cursos c ON a.id_curso = c.id_curso "
                + "INNER JOIN instructores i ON a.id_instructor = i.id_instructor "
                + "ORDER BY a.id_asignacion DESC";

        cnx.entablar(consulta, TConsultas);
    }

    private void cargarCombos() {
        cnx.seleccionar("SELECT nombre_completo FROM instructores ORDER BY nombre_completo", CBInstructor);
        cnx.seleccionar("SELECT nombre_curso FROM cursos ORDER BY nombre_curso", CBCurso);
    }

    private void limpiarCampos() {
        if (CBInstructor.getItemCount() > 0) {
            CBInstructor.setSelectedIndex(0);
        }
        if (CBCurso.getItemCount() > 0) {
            CBCurso.setSelectedIndex(0);
        }
        THorario.setText("");
        CBAula.setSelectedIndex(0);
        CBModalidad.setSelectedIndex(0);
        CBInstructor.requestFocus();
    }

    private void generarGrafica() {
        String query = "SELECT modalidad, COUNT(id_asignacion) FROM asignaciones GROUP BY modalidad";

        ArrayList<String> series = new ArrayList<>();
        series.add("Total");

        ArrayList<ArrayList<String>> datos = cnx.consultar(query);

        if (datos != null && !datos.isEmpty()) {
            GraficaXY graf = new GraficaXY("Asignaciones por Modalidad", "Modalidad", "Cantidad", series, datos);
            PFondo.removeAll();
            PFondo.add(graf.chartPanel);
            PFondo.updateUI();
        }
    }

    private String obtenerIdInstructor(String nombre) {
        // Busca el ID del instructor usando su nombre
        return cnx.buscarDato(
                "instructores", // Tabla donde buscar
                "id_instructor", // Columna que quiero obtener
                "nombre_completo", // Columna para la condición
                nombre // Valor de la condición
        );
    }

    private String obtenerIdCurso(String nombre) {
        // Busca el ID del curso usando su nombre
        return cnx.buscarDato(
                "cursos",
                "id_curso",
                "nombre_curso",
                nombre
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TConsultas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CBInstructor = new javax.swing.JComboBox<>();
        CBCurso = new javax.swing.JComboBox<>();
        THorario = new javax.swing.JTextField();
        CBModalidad = new javax.swing.JComboBox<>();
        CBAula = new javax.swing.JComboBox<>();
        Toolbar = new javax.swing.JToolBar();
        BNuevo = new javax.swing.JButton();
        BAgregar = new javax.swing.JButton();
        BActualizar = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BPDF = new javax.swing.JButton();
        BGrafica = new javax.swing.JButton();
        PFondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ASIGNACIONES");

        TConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TConsultasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TConsultas);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignar Curso a un Instructor:"));

        jLabel8.setText("Instructor:");

        jLabel9.setText("Curso:");

        jLabel10.setText("Horario de Sesión:");

        jLabel11.setText("Aula:");

        jLabel12.setText("Modalidad:");

        CBInstructor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "Virtual", "Híbrida" }));

        CBAula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aula 1", "Aula 2", "Aula 3", "Aula 4", "Aula 5" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CBInstructor, 0, 263, Short.MAX_VALUE)
                        .addComponent(CBCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(THorario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                    .addComponent(CBAula, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(THorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Toolbar.setBackground(new java.awt.Color(0, 102, 255));
        Toolbar.setRollover(true);

        BNuevo.setText("NUEVO");
        BNuevo.setFocusable(false);
        BNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNuevo.setOpaque(true);
        BNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BNuevo.addActionListener(this::BNuevoActionPerformed);
        Toolbar.add(BNuevo);

        BAgregar.setText("AGREGAR");
        BAgregar.setFocusable(false);
        BAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAgregar.setOpaque(true);
        BAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAgregar.addActionListener(this::BAgregarActionPerformed);
        Toolbar.add(BAgregar);

        BActualizar.setText("ACTUALIZAR");
        BActualizar.setFocusable(false);
        BActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BActualizar.setOpaque(true);
        BActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BActualizar.addActionListener(this::BActualizarActionPerformed);
        Toolbar.add(BActualizar);

        BEliminar.setText("ELIMINAR");
        BEliminar.setFocusable(false);
        BEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEliminar.setOpaque(true);
        BEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEliminar.addActionListener(this::BEliminarActionPerformed);
        Toolbar.add(BEliminar);

        BPDF.setText("PDF");
        BPDF.setFocusable(false);
        BPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BPDF.setOpaque(true);
        BPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BPDF.addActionListener(this::BPDFActionPerformed);
        Toolbar.add(BPDF);

        BGrafica.setText("GRÁFICA");
        BGrafica.setFocusable(false);
        BGrafica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BGrafica.setOpaque(true);
        BGrafica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BGrafica.addActionListener(this::BGraficaActionPerformed);
        Toolbar.add(BGrafica);

        PFondo.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        String nomInstructor = CBInstructor.getSelectedItem().toString();
        String nomCurso = CBCurso.getSelectedItem().toString();

        // Obtener los IDs
        String idInstructor = obtenerIdInstructor(nomInstructor);
        String idCurso = obtenerIdCurso(nomCurso);

        String horario = THorario.getText();
        String aula = CBAula.getSelectedItem().toString();
        String modalidad = CBModalidad.getSelectedItem().toString();

        String[] datos = {
            "",
            idCurso,
            idInstructor,
            THorario.getText(),
            CBAula.getSelectedItem().toString(),
            CBModalidad.getSelectedItem().toString()
        };

        if (cnx.insertar(tabla, datos) == 1) {
            JOptionPane.showMessageDialog(this, "Asignación agregada con éxito.");
            cargarDatos();
            limpiarCampos();
            generarGrafica();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar.");
        }
    }//GEN-LAST:event_BAgregarActionPerformed

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
        int fila = TConsultas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una asignación para editar.");
            return;
        }

        String idAsignacion = objToString(TConsultas.getValueAt(fila, 0));

        String nomInstructor = CBInstructor.getSelectedItem().toString();
        String nomCurso = CBCurso.getSelectedItem().toString();

        // Obtener los IDs
        String idInstructor = obtenerIdInstructor(nomInstructor);
        String idCurso = obtenerIdCurso(nomCurso);

        String[] datos = {
            idAsignacion,
            idCurso,
            idInstructor,
            THorario.getText(),
            CBAula.getSelectedItem().toString(),
            CBModalidad.getSelectedItem().toString()
        };

        if (cnx.actualizar(tabla, datos) == 1) {
            JOptionPane.showMessageDialog(this, "Asignación actualizada.");
            cargarDatos();
            limpiarCampos();
            generarGrafica();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar.");
        }
    }//GEN-LAST:event_BActualizarActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        int fila = TConsultas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.");
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "¿Eliminar asignación?", "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            String idAsignacion = objToString(TConsultas.getValueAt(fila, 0));
            String[] datos = {idAsignacion};

            if (cnx.borrar(tabla, datos) == 1) {
                JOptionPane.showMessageDialog(this, "Eliminado correctamente.");
                cargarDatos();
                limpiarCampos();
                generarGrafica();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar.");
            }
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPDFActionPerformed
        String consulta = "SELECT i.nombre_completo AS Instructor, c.nombre_curso AS Curso, "
                + "a.horario_especifico AS Horario, a.aula AS Aula, a.modalidad AS Modalidad "
                + "FROM asignaciones a "
                + "JOIN cursos c ON a.id_curso = c.id_curso "
                + "JOIN instructores i ON a.id_instructor = i.id_instructor "
                + "ORDER BY i.nombre_completo";

        float[] anchos = {3f, 3f, 2f, 1.5f, 1.5f}; // Ajuste de anchos para 5 columnas

        if (cnx.crearPDF("Casa de la Cultura", "Reporte de Asignaciones", consulta, anchos, "ReporteAsignaciones") == 1) {
            cnx.visualizarPDF("ReporteAsignaciones");
        }
    }//GEN-LAST:event_BPDFActionPerformed

    private void BGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGraficaActionPerformed
        generarGrafica();
    }//GEN-LAST:event_BGraficaActionPerformed

    private void TConsultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TConsultasMousePressed
        int fila = TConsultas.getSelectedRow();

        if (fila >= 0) {
            String nombreCurso = objToString(TConsultas.getValueAt(fila, 1));
            String nombreInstructor = objToString(TConsultas.getValueAt(fila, 2));
            String horario = objToString(TConsultas.getValueAt(fila, 3));
            String aula = objToString(TConsultas.getValueAt(fila, 4));
            String modalidad = objToString(TConsultas.getValueAt(fila, 5));

            CBCurso.setSelectedItem(nombreCurso);
            CBInstructor.setSelectedItem(nombreInstructor);
            THorario.setText(horario);
            CBAula.setSelectedItem(aula);
            CBModalidad.setSelectedItem(modalidad);
        }
    }//GEN-LAST:event_TConsultasMousePressed

    private String objToString(Object o) {
        return o != null ? o.toString() : "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BGrafica;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BPDF;
    private javax.swing.JComboBox<String> CBAula;
    private javax.swing.JComboBox<String> CBCurso;
    private javax.swing.JComboBox<String> CBInstructor;
    private javax.swing.JComboBox<String> CBModalidad;
    private javax.swing.JPanel PFondo;
    private javax.swing.JTable TConsultas;
    private javax.swing.JTextField THorario;
    private javax.swing.JToolBar Toolbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
