
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author juliann
 */
public class FInstructores extends javax.swing.JFrame {

    ConexionHR cnx;
    String tabla = "instructores";

    public FInstructores(ConexionHR cnx) {
        initComponents();

        this.cnx = cnx;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Gestión de Instructores - Casa de Cultura");
        cargarDatos();
        generarGrafica();
    }

    private void cargarDatos() {
        String instructores = "SELECT * FROM instructores";

        int resultado = cnx.entablar(instructores, TConsultas);

        if (resultado == 0) {
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los datos o la tabla está vacía.");
        }
    }

    private void limpiarCampos() {
        TNombre.setText("");
        TCedula.setText("");
        TEspecialidad.setText("");
        TTelefono.setText("");
        TCorreo.setText("");
        TNombre.requestFocus();
    }

    private void generarGrafica() {
        String consulta = "SELECT i.nombre_completo, COUNT(a.id_curso) "
                + "FROM instructores i "
                + "INNER JOIN asignaciones a ON i.id_instructor = a.id_instructor "
                + "GROUP BY i.nombre_completo";

        // Preparar las series (La leyenda de qué representa la barra)
        ArrayList<String> series = new ArrayList<>();
        series.add("Cursos Asignados");

        ArrayList<ArrayList<String>> datos = cnx.consultar(consulta);

        if (datos == null || datos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay cursos asignados para graficar.");
            return;
        }

        // Título, Etiqueta Eje X, Etiqueta Eje Y, Series, Datos
        GraficaXY grafica = new GraficaXY("Carga de Trabajo por Instructor", "Instructor", "Cantidad", series, datos);

        PFondo.removeAll();
        PFondo.add(grafica.chartPanel);
        PFondo.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TConsultas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TEspecialidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TCedula = new javax.swing.JTextField();
        Toolbar = new javax.swing.JToolBar();
        BNuevo = new javax.swing.JButton();
        BAgregar = new javax.swing.JButton();
        BActualizar = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BPDF = new javax.swing.JButton();
        BGrafica = new javax.swing.JButton();
        PFondo = new javax.swing.JPanel();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INSTRUCTORES");

        TConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TConsultasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TConsultas);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Instructor:"));

        jLabel2.setText("Nombre Completo:");

        jLabel3.setText("Teléfono:");

        jLabel4.setText("Correo Electrónico:");

        jLabel5.setText("Especialidad:");

        jLabel6.setText("Cédula:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TTelefono)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(TNombre))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(TEspecialidad)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCedula))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Toolbar.setBackground(new java.awt.Color(0, 102, 255));
        Toolbar.setRollover(true);

        BNuevo.setText("NUEVO");
        BNuevo.setFocusable(false);
        BNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNuevo.setOpaque(true);
        BNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BNuevo.addActionListener(this::BNuevoActionPerformed);
        Toolbar.add(BNuevo);

        BAgregar.setText("AGREGAR");
        BAgregar.setFocusable(false);
        BAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAgregar.setOpaque(true);
        BAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAgregar.addActionListener(this::BAgregarActionPerformed);
        Toolbar.add(BAgregar);

        BActualizar.setText("ACTUALIZAR");
        BActualizar.setFocusable(false);
        BActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BActualizar.setOpaque(true);
        BActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BActualizar.addActionListener(this::BActualizarActionPerformed);
        Toolbar.add(BActualizar);

        BEliminar.setText("ELIMINAR");
        BEliminar.setFocusable(false);
        BEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEliminar.setOpaque(true);
        BEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEliminar.addActionListener(this::BEliminarActionPerformed);
        Toolbar.add(BEliminar);

        BPDF.setText("PDF");
        BPDF.setFocusable(false);
        BPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BPDF.setOpaque(true);
        BPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BPDF.addActionListener(this::BPDFActionPerformed);
        Toolbar.add(BPDF);

        BGrafica.setText("GRÁFICA");
        BGrafica.setFocusable(false);
        BGrafica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BGrafica.setOpaque(true);
        BGrafica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BGrafica.addActionListener(this::BGraficaActionPerformed);
        Toolbar.add(BGrafica);

        PFondo.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        String[] datos = {
            "", // id vacïo para autoincremento
            TNombre.getText(),
            TCedula.getText(),
            TEspecialidad.getText(),
            TTelefono.getText(),
            TCorreo.getText()
        };

        if (cnx.insertar(tabla, datos) == 1) {
            JOptionPane.showMessageDialog(this, "Instructor agregado");
            cargarDatos();
            limpiarCampos();
            generarGrafica();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar.");
        }
    }//GEN-LAST:event_BAgregarActionPerformed

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
        int fila = TConsultas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un instructor para editar.");
            return;
        }

        String id = TConsultas.getValueAt(fila, 0).toString();

        String[] datos = {
            id,
            TNombre.getText(),
            TCedula.getText(),
            TEspecialidad.getText(),
            TTelefono.getText(),
            TCorreo.getText()
        };

        if (cnx.actualizar(tabla, datos) == 1) {
            JOptionPane.showMessageDialog(this, "Instructor actualizado");
            cargarDatos();
            limpiarCampos();
            generarGrafica();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar.");
        }
    }//GEN-LAST:event_BActualizarActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        int fila = TConsultas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un instructor para eliminar.");
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "¿Eliminar este instructor?", "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            String id = TConsultas.getValueAt(fila, 0).toString();
            // El método borrar necesita un array donde la pos 0 sea el ID
            String[] datos = {id};

            if (cnx.borrar(tabla, datos) == 1) {
                JOptionPane.showMessageDialog(this, "Instructor eliminado");
                cargarDatos();
                limpiarCampos();
                generarGrafica();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar.");
            }
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPDFActionPerformed
        String query = "SELECT i.nombre_completo AS Instructor, c.nombre_curso AS Curso, "
                + "a.aula AS Aula, a.horario_especifico AS Horario "
                + "FROM instructores i "
                + "INNER JOIN asignaciones a ON i.id_instructor = a.id_instructor "
                + "INNER JOIN cursos c ON a.id_curso = c.id_curso "
                + "ORDER BY i.nombre_completo";

        float[] anchos = new float[]{3f, 3f, 2f, 2f};

        // Título del Doc, Encabezado Tabla, Query, Anchos, Nombre Archivo (sin .pdf)
        int estado = cnx.crearPDF("Casa de la Cultura", "Reporte de Cursos Asignados", query, anchos, "ReporteInstructores");

        if (estado == 1) {
            cnx.visualizarPDF("ReporteInstructores");
        } else {
            JOptionPane.showMessageDialog(this, "Error al generar PDF.");
        }
    }//GEN-LAST:event_BPDFActionPerformed

    private void BGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGraficaActionPerformed
        generarGrafica();
    }//GEN-LAST:event_BGraficaActionPerformed

    private void TConsultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TConsultasMousePressed
        int fila = TConsultas.getSelectedRow();
        if (fila >= 0) {
            String nombre = objToString(TConsultas.getValueAt(fila, 1));
            String cedula = objToString(TConsultas.getValueAt(fila, 2));
            String especialidad = objToString(TConsultas.getValueAt(fila, 3));
            String telefono = objToString(TConsultas.getValueAt(fila, 4));
            String correo = objToString(TConsultas.getValueAt(fila, 5));

            TNombre.setText(nombre);
            TCedula.setText(cedula);
            TEspecialidad.setText(especialidad);
            TTelefono.setText(telefono);
            TCorreo.setText(correo);
        }
    }//GEN-LAST:event_TConsultasMousePressed

    private String objToString(Object o) {
        return o != null ? o.toString() : "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BGrafica;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BPDF;
    private javax.swing.JPanel PFondo;
    private javax.swing.JTextField TCedula;
    private javax.swing.JTable TConsultas;
    private javax.swing.JTextField TCorreo;
    private javax.swing.JTextField TEspecialidad;
    private javax.swing.JTextField TNombre;
    private javax.swing.JTextField TTelefono;
    private javax.swing.JToolBar Toolbar;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
