
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author juliann
 */
public class FInstructores extends javax.swing.JFrame {

    ConexionHR cnx;
    String tabla = "instructores";

    public FInstructores(ConexionHR cnx) {
        initComponents();

        this.cnx = cnx;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Gestión de Instructores - Casa de Cultura");
        cargarDatos();
        generarGrafica();

        DefaultTableModel modelo = (DefaultTableModel) TConsultas.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(modelo);
        TConsultas.setRowSorter(sorter);
    }

    private void cargarDatos() {
        // obtener el texto de búsqueda y evitar nulos
        String busqueda = TBuscar.getText().trim();

        String orden = "";
        String direccion = "ASC";
        if (CBOrden.getSelectedItem() != null) {
            orden = CBOrden.getSelectedItem().toString();
        } else {
            orden = "nombre_completo"; // Valor por defecto
        }

        if (CBDireccion.getSelectedItem() != null) {
            direccion = CBDireccion.getSelectedItem().toString();
        }

        // el procedimiento pide (p_busqueda, p_orden, p_direccion)
        String consulta = "CALL obtener_instructores('" + busqueda + "', '" + orden + "', '" + direccion + "')";

        int resultado = cnx.entablar(consulta, TConsultas);

        if (resultado == 0) {
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los datos o la tabla está vacía.");
        }
    }

    private void limpiarCampos() {
        TNombre.setText("");
        TCedula.setText("");
        TEspecialidad.setText("");
        TTelefono.setText("");
        TCorreo.setText("");
        TNombre.requestFocus();
    }

    private void generarGrafica() {
        String consulta = "CALL contar_talleres_por_instructor()";

        // Preparar las series (La leyenda de qué representa la barra)
        ArrayList<String> series = new ArrayList<>();
        series.add("Talleres Asignados");

        ArrayList<ArrayList<String>> datos = cnx.consultar(consulta);

        if (datos == null || datos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay talleres asignados para graficar.");
            return;
        }

        // Título, Etiqueta Eje X, Etiqueta Eje Y, Series, Datos
        GraficaXY grafica = new GraficaXY("Carga de Trabajo por Instructor", "Instructor", "Cantidad", series, datos);

        PFondo.removeAll();
        PFondo.add(grafica.chartPanel);
        PFondo.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TConsultas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TEspecialidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TCedula = new javax.swing.JTextField();
        Toolbar = new javax.swing.JToolBar();
        BNuevo = new javax.swing.JButton();
        BAgregar = new javax.swing.JButton();
        BActualizar = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BPDF = new javax.swing.JButton();
        BGrafica = new javax.swing.JButton();
        PFondo = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel7 = new javax.swing.JLabel();
        CBOrden = new javax.swing.JComboBox<>();
        CBDireccion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TBuscar = new javax.swing.JTextField();
        jToolBar2 = new javax.swing.JToolBar();
        BTodos = new javax.swing.JButton();
        BAsignados = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INSTRUCTORES");

        TConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TConsultasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TConsultas);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Instructor:"));

        jLabel2.setText("Nombre Completo:");

        jLabel3.setText("Teléfono:");

        jLabel4.setText("Correo Electrónico:");

        jLabel5.setText("Especialidad:");

        jLabel6.setText("Cédula:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TTelefono)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(TNombre))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(TEspecialidad)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCedula))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Toolbar.setBackground(new java.awt.Color(0, 229, 255));
        Toolbar.setRollover(true);

        BNuevo.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpiar.png"))); // NOI18N
        BNuevo.setText("NUEVO");
        BNuevo.setFocusable(false);
        BNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNuevo.setOpaque(true);
        BNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BNuevo.addActionListener(this::BNuevoActionPerformed);
        Toolbar.add(BNuevo);

        BAgregar.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar-archivo.png"))); // NOI18N
        BAgregar.setText("AGREGAR");
        BAgregar.setFocusable(false);
        BAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAgregar.setOpaque(true);
        BAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAgregar.addActionListener(this::BAgregarActionPerformed);
        Toolbar.add(BAgregar);

        BActualizar.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        BActualizar.setText("ACTUALIZAR");
        BActualizar.setFocusable(false);
        BActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BActualizar.setOpaque(true);
        BActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BActualizar.addActionListener(this::BActualizarActionPerformed);
        Toolbar.add(BActualizar);

        BEliminar.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        BEliminar.setText("ELIMINAR");
        BEliminar.setFocusable(false);
        BEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEliminar.setOpaque(true);
        BEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEliminar.addActionListener(this::BEliminarActionPerformed);
        Toolbar.add(BEliminar);

        BPDF.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pdf.png"))); // NOI18N
        BPDF.setText("PDF");
        BPDF.setFocusable(false);
        BPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BPDF.setOpaque(true);
        BPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BPDF.addActionListener(this::BPDFActionPerformed);
        Toolbar.add(BPDF);

        BGrafica.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BGrafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/barra-grafica.png"))); // NOI18N
        BGrafica.setText("GRÁFICA");
        BGrafica.setFocusable(false);
        BGrafica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BGrafica.setOpaque(true);
        BGrafica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BGrafica.addActionListener(this::BGraficaActionPerformed);
        Toolbar.add(BGrafica);

        PFondo.setLayout(new java.awt.GridLayout(1, 1));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        jLabel7.setText("ORDEN:");
        jToolBar1.add(jLabel7);

        CBOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre_completo", "id_instructor", "especialidad", "cedula_profesional", "telefono", "email" }));
        CBOrden.addItemListener(this::CBOrdenItemStateChanged);
        jToolBar1.add(CBOrden);

        CBDireccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASC", "DESC" }));
        CBDireccion.addItemListener(this::CBDireccionItemStateChanged);
        jToolBar1.add(CBDireccion);

        jLabel8.setText("BUSCAR:");
        jToolBar1.add(jLabel8);

        TBuscar.setMaximumSize(new java.awt.Dimension(160, 35));
        TBuscar.setMinimumSize(new java.awt.Dimension(160, 35));
        TBuscar.setPreferredSize(new java.awt.Dimension(160, 35));
        TBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TBuscarKeyReleased(evt);
            }
        });
        jToolBar1.add(TBuscar);

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setRollover(true);

        BTodos.setBackground(new java.awt.Color(0, 229, 255));
        BTodos.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BTodos.setText("TODOS");
        BTodos.setFocusable(false);
        BTodos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTodos.setOpaque(true);
        BTodos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTodos.addActionListener(this::BTodosActionPerformed);
        jToolBar2.add(BTodos);

        BAsignados.setBackground(new java.awt.Color(0, 229, 255));
        BAsignados.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BAsignados.setForeground(new java.awt.Color(51, 51, 51));
        BAsignados.setText("TALLERES ASIGNADOS");
        BAsignados.setFocusable(false);
        BAsignados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAsignados.setOpaque(true);
        BAsignados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAsignados.addActionListener(this::BAsignadosActionPerformed);
        jToolBar2.add(BAsignados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        String[] datos = {
            "", // id vacïo para autoincremento
            TNombre.getText(),
            TCedula.getText(),
            TEspecialidad.getText(),
            TTelefono.getText(),
            TCorreo.getText()
        };

        if (cnx.insertar(tabla, datos) == 1) {
            JOptionPane.showMessageDialog(this, "Instructor agregado");
            cargarDatos();
            limpiarCampos();
            generarGrafica();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar.");
        }
    }//GEN-LAST:event_BAgregarActionPerformed

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
        int fila = TConsultas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un instructor para editar.");
            return;
        }

        String id = TConsultas.getValueAt(fila, 0).toString();

        String[] datos = {
            id,
            TNombre.getText(),
            TCedula.getText(),
            TEspecialidad.getText(),
            TTelefono.getText(),
            TCorreo.getText()
        };

        if (cnx.actualizar(tabla, datos) == 1) {
            JOptionPane.showMessageDialog(this, "Instructor actualizado");
            cargarDatos();
            limpiarCampos();
            generarGrafica();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar.");
        }
    }//GEN-LAST:event_BActualizarActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        int fila = TConsultas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un instructor para eliminar.");
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "¿Eliminar este instructor?", "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            String id = TConsultas.getValueAt(fila, 0).toString();
            // El método borrar necesita un array donde la pos 0 sea el ID
            String[] datos = {id};

            if (cnx.borrar(tabla, datos) == 1) {
                JOptionPane.showMessageDialog(this, "Instructor eliminado");
                cargarDatos();
                limpiarCampos();
                generarGrafica();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar.");
            }
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPDFActionPerformed
        int fila = TConsultas.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un instructor de la tabla para generar su reporte.");
            return;
        }

        // obtener el ID del instructor de la fila seleccionada (Columna 0)
        String idInstructor = TConsultas.getValueAt(fila, 0).toString();
        String nombreInstructor = TConsultas.getValueAt(fila, 1).toString();

        String query = "SELECT i.nombre_completo AS Instructor, t.nombre_taller AS Taller, "
                + "a.aula AS Aula, a.horario_especifico AS Horario "
                + "FROM instructores i "
                + "INNER JOIN asignaciones a ON i.id_instructor = a.id_instructor "
                + "INNER JOIN talleres t ON a.id_taller = t.id_taller "
                + "WHERE i.id_instructor = " + idInstructor + " "
                + "ORDER BY t.nombre_taller";

        float[] anchos = new float[]{3f, 3f, 2f, 2f};

        String tituloReporte = "Carga Académica: " + nombreInstructor;

        int estado = cnx.crearPDF("Casa de la Cultura", tituloReporte, query, anchos, "Reporte_Instructor_" + idInstructor);

        if (estado == 1) {
            cnx.visualizarPDF("Reporte_Instructor_" + idInstructor);
        } else {
            JOptionPane.showMessageDialog(this, "Error al generar PDF. Asegúrate de que el instructor tenga talleres asignados.");
        }
    }//GEN-LAST:event_BPDFActionPerformed

    private void BGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGraficaActionPerformed
        generarGrafica();
    }//GEN-LAST:event_BGraficaActionPerformed

    private void TConsultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TConsultasMousePressed
        int fila = TConsultas.getSelectedRow();
        if (fila >= 0) {
            String nombre = objToString(TConsultas.getValueAt(fila, 1));
            String cedula = objToString(TConsultas.getValueAt(fila, 2));
            String especialidad = objToString(TConsultas.getValueAt(fila, 3));
            String telefono = objToString(TConsultas.getValueAt(fila, 4));
            String correo = objToString(TConsultas.getValueAt(fila, 5));

            TNombre.setText(nombre);
            TCedula.setText(cedula);
            TEspecialidad.setText(especialidad);
            TTelefono.setText(telefono);
            TCorreo.setText(correo);
        }
    }//GEN-LAST:event_TConsultasMousePressed

    private void BTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTodosActionPerformed
        String sql = "CALL obtener_instructores('', 'nombre_completo', 'ASC')";
        cnx.entablar(sql, TConsultas);
    }//GEN-LAST:event_BTodosActionPerformed

    private void CBOrdenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBOrdenItemStateChanged
        cargarDatos();
    }//GEN-LAST:event_CBOrdenItemStateChanged

    private void BAsignadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAsignadosActionPerformed
        String consulta = "CALL contar_talleres_por_instructor()";
        cnx.entablar(consulta, TConsultas);
    }//GEN-LAST:event_BAsignadosActionPerformed

    private void TBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBuscarKeyReleased
        cargarDatos();
    }//GEN-LAST:event_TBuscarKeyReleased

    private void CBDireccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBDireccionItemStateChanged
        cargarDatos();
    }//GEN-LAST:event_CBDireccionItemStateChanged

    private String objToString(Object o) {
        return o != null ? o.toString() : "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BAsignados;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BGrafica;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BPDF;
    private javax.swing.JButton BTodos;
    private javax.swing.JComboBox<String> CBDireccion;
    private javax.swing.JComboBox<String> CBOrden;
    private javax.swing.JPanel PFondo;
    private javax.swing.JTextField TBuscar;
    private javax.swing.JTextField TCedula;
    private javax.swing.JTable TConsultas;
    private javax.swing.JTextField TCorreo;
    private javax.swing.JTextField TEspecialidad;
    private javax.swing.JTextField TNombre;
    private javax.swing.JTextField TTelefono;
    private javax.swing.JToolBar Toolbar;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
