/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author juliann
 */
public class FMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FMenu.class.getName());

    /**
     * Creates new form FMenu
     */
    
    String url = "http://127.0.0.1:9000/mysql.php";
    ConexionHR cnx = new ConexionHR(url);
    
    public FMenu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BIstructores = new javax.swing.JButton();
        BTalleres = new javax.swing.JButton();
        BAsignacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BIstructores.setBackground(new java.awt.Color(0, 102, 255));
        BIstructores.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BIstructores.setForeground(new java.awt.Color(255, 255, 255));
        BIstructores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/instructor-icono.png"))); // NOI18N
        BIstructores.setText("INSTRUCTORES");
        BIstructores.addActionListener(this::BIstructoresActionPerformed);

        BTalleres.setBackground(new java.awt.Color(0, 102, 255));
        BTalleres.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BTalleres.setForeground(new java.awt.Color(255, 255, 255));
        BTalleres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cursos-icono.png"))); // NOI18N
        BTalleres.setText("TALLERES");
        BTalleres.addActionListener(this::BTalleresActionPerformed);

        BAsignacion.setBackground(new java.awt.Color(0, 102, 255));
        BAsignacion.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BAsignacion.setForeground(new java.awt.Color(255, 255, 255));
        BAsignacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/asignar-icono-1.png"))); // NOI18N
        BAsignacion.setText("ASIGNACIÓN");
        BAsignacion.addActionListener(this::BAsignacionActionPerformed);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CASA DE LA CULTURA - TALLERES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BTalleres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BAsignacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BIstructores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BIstructores, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTalleresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTalleresActionPerformed
        FTalleres vTalleres = new FTalleres(cnx);
        vTalleres.setVisible(true);
    }//GEN-LAST:event_BTalleresActionPerformed

    private void BIstructoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIstructoresActionPerformed
        FInstructores vInstructores = new FInstructores(cnx);
        vInstructores.setVisible(true);
    }//GEN-LAST:event_BIstructoresActionPerformed

    private void BAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAsignacionActionPerformed
        FAsignaciones vAsignaciones = new FAsignaciones(cnx);
        vAsignaciones.setVisible(true);
    }//GEN-LAST:event_BAsignacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAsignacion;
    private javax.swing.JButton BIstructores;
    private javax.swing.JButton BTalleres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
