
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author juliann
 */
public class FTalleres extends javax.swing.JFrame {

    ConexionHR cnx;
    String tabla = "talleres";

    public FTalleres(ConexionHR cnx) {
        initComponents();

        this.cnx = cnx;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Gestión de Talleres - Casa de Cultura");

        cargarDatos();
        generarGrafica();

        DefaultTableModel model = (DefaultTableModel) TConsultas.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        TConsultas.setRowSorter(sorter);

    }

    private void cargarDatos() {
        String busqueda = TBuscar.getText().trim();

        String orden = "nombre_taller"; // Valor por defecto
        if (CBOrden.getSelectedItem() != null) {
            orden = CBOrden.getSelectedItem().toString();
        }

        // Estructura: CALL obtener_talleres(busqueda, campo_orden, direccion)
        String consulta = "CALL obtener_talleres('" + busqueda + "', '" + orden + "', 'ASC')";

        int resultado = cnx.entablar(consulta, TConsultas);

        if (resultado == 0 && busqueda.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los datos.");
        }
    }

    private void limpiarCampos() {
        TNombre.setText("");
        SCosto.setValue(0);
        CBNivel.setSelectedIndex(0);
        TDescripcion.setText("");
        DCFechaInicio.setDate(null);
        DCFechaFin.setDate(null);
        TNombre.requestFocus();
    }

    private void generarGrafica() {
        // String consulta = "CALL obtener_talleres_por_costo()";
        String consulta = "SELECT nivel, COUNT(id_taller) FROM talleres GROUP BY nivel";

        ArrayList<String> series = new ArrayList<>();
        series.add("Costo Semestral");

        ArrayList<ArrayList<String>> datos = cnx.consultar(consulta);

        if (datos == null || datos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay datos para graficar.");
            return;
        }

        GraficaXY grafica = new GraficaXY("Distribución de Talleres por Nivel", "Taller", "Costo ($)", series, datos);

        PFondo.removeAll();
        PFondo.add(grafica.chartPanel);
        PFondo.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TConsultas = new javax.swing.JTable();
        Toolbar = new javax.swing.JToolBar();
        BNuevo = new javax.swing.JButton();
        BAgregar = new javax.swing.JButton();
        BActualizar = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        SReporteCosto = new javax.swing.JSpinner();
        BPDF = new javax.swing.JButton();
        BGrafica = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SCosto = new javax.swing.JSpinner();
        CBNivel = new javax.swing.JComboBox<>();
        DCFechaInicio = new com.toedter.calendar.JDateChooser();
        DCFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TDescripcion = new javax.swing.JTextArea();
        PFondo = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel8 = new javax.swing.JLabel();
        CBOrden = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TBuscar = new javax.swing.JTextField();
        jToolBar2 = new javax.swing.JToolBar();
        BTodos = new javax.swing.JButton();
        BCostos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TALLERES");

        TConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TConsultasMousePressed(evt);
            }
        });
        TConsultas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TConsultasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TConsultas);

        Toolbar.setBackground(new java.awt.Color(255, 82, 82));
        Toolbar.setRollover(true);

        BNuevo.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpiar.png"))); // NOI18N
        BNuevo.setText("NUEVO");
        BNuevo.setFocusable(false);
        BNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNuevo.setOpaque(true);
        BNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BNuevo.addActionListener(this::BNuevoActionPerformed);
        Toolbar.add(BNuevo);

        BAgregar.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar-archivo.png"))); // NOI18N
        BAgregar.setText("AGREGAR");
        BAgregar.setFocusable(false);
        BAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAgregar.setOpaque(true);
        BAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAgregar.addActionListener(this::BAgregarActionPerformed);
        Toolbar.add(BAgregar);

        BActualizar.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        BActualizar.setText("ACTUALIZAR");
        BActualizar.setFocusable(false);
        BActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BActualizar.setOpaque(true);
        BActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BActualizar.addActionListener(this::BActualizarActionPerformed);
        Toolbar.add(BActualizar);

        BEliminar.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        BEliminar.setText("ELIMINAR");
        BEliminar.setFocusable(false);
        BEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEliminar.setOpaque(true);
        BEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEliminar.addActionListener(this::BEliminarActionPerformed);
        Toolbar.add(BEliminar);

        jLabel10.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TALLERES CON COSTO MAYOR A:");
        Toolbar.add(jLabel10);

        SReporteCosto.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 100));
        SReporteCosto.setMaximumSize(new java.awt.Dimension(150, 25));
        SReporteCosto.setMinimumSize(new java.awt.Dimension(150, 25));
        SReporteCosto.setPreferredSize(new java.awt.Dimension(150, 25));
        Toolbar.add(SReporteCosto);

        BPDF.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pdf.png"))); // NOI18N
        BPDF.setText("PDF");
        BPDF.setFocusable(false);
        BPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BPDF.setOpaque(true);
        BPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BPDF.addActionListener(this::BPDFActionPerformed);
        Toolbar.add(BPDF);

        BGrafica.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BGrafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/barra-grafica.png"))); // NOI18N
        BGrafica.setText("GRÁFICA");
        BGrafica.setFocusable(false);
        BGrafica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BGrafica.setOpaque(true);
        BGrafica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BGrafica.addActionListener(this::BGraficaActionPerformed);
        Toolbar.add(BGrafica);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Taller:"));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Costo Semanal:");

        jLabel4.setText("Nivel:");

        jLabel5.setText("Fecha de Inicio:");

        jLabel6.setText("Fecha de Finalización:");

        CBNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básico", "Intermedio", "Avanzado" }));

        jLabel7.setText("Descripción:");

        TDescripcion.setColumns(20);
        TDescripcion.setRows(5);
        jScrollPane2.setViewportView(TDescripcion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(DCFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DCFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DCFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DCFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PFondo.setLayout(new java.awt.GridLayout(1, 1));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        jLabel8.setText("ORDEN:");
        jToolBar1.add(jLabel8);

        CBOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre_taller", "id_taller", "costo_semestral", "nivel", "fecha_inicio", "fecha_fin" }));
        CBOrden.addItemListener(this::CBOrdenItemStateChanged);
        jToolBar1.add(CBOrden);

        jLabel9.setText("BUSCAR:");
        jToolBar1.add(jLabel9);

        TBuscar.setMaximumSize(new java.awt.Dimension(160, 35));
        TBuscar.setMinimumSize(new java.awt.Dimension(160, 35));
        TBuscar.setPreferredSize(new java.awt.Dimension(160, 35));
        TBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TBuscarKeyTyped(evt);
            }
        });
        jToolBar1.add(TBuscar);

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setRollover(true);

        BTodos.setBackground(new java.awt.Color(255, 82, 82));
        BTodos.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BTodos.setForeground(new java.awt.Color(255, 255, 255));
        BTodos.setText("TODOS");
        BTodos.setFocusable(false);
        BTodos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTodos.setOpaque(true);
        BTodos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTodos.addActionListener(this::BTodosActionPerformed);
        jToolBar2.add(BTodos);

        BCostos.setBackground(new java.awt.Color(255, 82, 82));
        BCostos.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        BCostos.setForeground(new java.awt.Color(255, 255, 255));
        BCostos.setText("POR NIVEL");
        BCostos.setFocusable(false);
        BCostos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BCostos.setOpaque(true);
        BCostos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BCostos.addActionListener(this::BCostosActionPerformed);
        jToolBar2.add(BCostos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TConsultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TConsultasMousePressed
        int fila = TConsultas.getSelectedRow();

        if (fila >= 0) {
            String nombre = objToString(TConsultas.getValueAt(fila, 1));
            String descripcion = objToString(TConsultas.getValueAt(fila, 2));
            String costoStr = objToString(TConsultas.getValueAt(fila, 3));
            String nivel = objToString(TConsultas.getValueAt(fila, 4));
            String fInicioStr = objToString(TConsultas.getValueAt(fila, 5));
            String fFinStr = objToString(TConsultas.getValueAt(fila, 6));

            TNombre.setText(nombre);
            TDescripcion.setText(descripcion);
            CBNivel.setSelectedItem(nivel);

            try {
                double costo = Double.parseDouble(costoStr);
                SCosto.setValue(costo);
            } catch (NumberFormatException e) {
                System.out.println("Error al convertir costo: " + e.getMessage());
                SCosto.setValue(0.0);
            }

            DCFechaInicio.setDate(cnx.toDate(fInicioStr));
            DCFechaFin.setDate(cnx.toDate(fFinStr));
        }
    }//GEN-LAST:event_TConsultasMousePressed

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        if (DCFechaInicio.getDate() == null || DCFechaFin.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona las fechas de inicio y fin.");
            return;
        }

        String[] datos = {
            "", // ID autoincrementable
            TNombre.getText(),
            TDescripcion.getText(),
            SCosto.getValue().toString(),
            CBNivel.getSelectedItem().toString(),
            cnx.toSQL(DCFechaInicio.getDate()),
            cnx.toSQL(DCFechaFin.getDate())
        };

        if (cnx.insertar(tabla, datos) == 1) {
            JOptionPane.showMessageDialog(this, "Taller agregado exitosamente.");
            cargarDatos();
            limpiarCampos();
            generarGrafica();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el taller.");
        }
    }//GEN-LAST:event_BAgregarActionPerformed

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
        int fila = TConsultas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un taller de la tabla para actualizar.");
            return;
        }

        if (DCFechaInicio.getDate() == null || DCFechaFin.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Las fechas no pueden estar vacías.");
            return;
        }

        String id = TConsultas.getValueAt(fila, 0).toString();

        String[] datos = {
            id,
            TNombre.getText(),
            TDescripcion.getText(),
            SCosto.getValue().toString(),
            CBNivel.getSelectedItem().toString(),
            cnx.toSQL(DCFechaInicio.getDate()),
            cnx.toSQL(DCFechaFin.getDate())
        };

        if (cnx.actualizar(tabla, datos) == 1) {
            JOptionPane.showMessageDialog(this, "Taller actualizado exitosamente.");
            cargarDatos();
            limpiarCampos();
            generarGrafica();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar.");
        }
    }//GEN-LAST:event_BActualizarActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        int fila = TConsultas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un taller para eliminar.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de eliminar este taller?\nSe borrarán también sus asignaciones.",
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            String id = TConsultas.getValueAt(fila, 0).toString();
            String[] datos = {id};

            if (cnx.borrar(tabla, datos) == 1) {
                JOptionPane.showMessageDialog(this, "Taller eliminado.");
                cargarDatos();
                limpiarCampos();
                generarGrafica();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar.");
            }
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPDFActionPerformed
        // 1. Verificar si se estableció un costo filtro en el Spinner
        double costoLimite = 0;
        try {
            Object val = SReporteCosto.getValue();
            if (val instanceof Number) {
                costoLimite = ((Number) val).doubleValue();
            }
        } catch (Exception e) {
            costoLimite = 0;
        }

        if (costoLimite > 0) {
            String query = "SELECT nombre_taller AS Taller, nivel AS Nivel, "
                    + "costo_semestral AS Costo, fecha_inicio AS Inicio, fecha_fin AS Fin "
                    + "FROM talleres "
                    + "WHERE costo_semestral > " + costoLimite + " " // Changed from < to >
                    + "ORDER BY costo_semestral ASC";

            float[] anchos = {3f, 2f, 1.5f, 2f, 2f};
            String titulo = "Talleres con Costo Mayor a $" + costoLimite; // Changed title
            String nombreArchivo = "Reporte_Talleres_Mayor_" + costoLimite; // Changed filename

            int estado = cnx.crearPDF("Casa de la Cultura", titulo, query, anchos, nombreArchivo);

            if (estado == 1) {
                cnx.visualizarPDF(nombreArchivo);
            } else {
                JOptionPane.showMessageDialog(this, "Error al generar el reporte de costos.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un costo mayor a 0 en el campo superior para generar el reporte.");
        }
    }//GEN-LAST:event_BPDFActionPerformed

    private void BGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGraficaActionPerformed
        generarGrafica();
    }//GEN-LAST:event_BGraficaActionPerformed

    private void CBOrdenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBOrdenItemStateChanged
        cargarDatos();
    }//GEN-LAST:event_CBOrdenItemStateChanged

    private void TBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBuscarKeyTyped
        cargarDatos();
    }//GEN-LAST:event_TBuscarKeyTyped

    private void BTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTodosActionPerformed
        String consultas = "CALL obtener_talleres('', 'nombre_taller', 'ASC')";
        cnx.entablar(consultas, TConsultas);
    }//GEN-LAST:event_BTodosActionPerformed

    private void BCostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCostosActionPerformed
        String consulta = "SELECT nivel, COUNT(id_taller) FROM talleres GROUP BY nivel";
        cnx.entablar(consulta, TConsultas);
    }//GEN-LAST:event_BCostosActionPerformed

    private void TConsultasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TConsultasKeyReleased
        cargarDatos();
    }//GEN-LAST:event_TConsultasKeyReleased

    private String objToString(Object o) {
        return o != null ? o.toString() : "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BCostos;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BGrafica;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BPDF;
    private javax.swing.JButton BTodos;
    private javax.swing.JComboBox<String> CBNivel;
    private javax.swing.JComboBox<String> CBOrden;
    private com.toedter.calendar.JDateChooser DCFechaFin;
    private com.toedter.calendar.JDateChooser DCFechaInicio;
    private javax.swing.JPanel PFondo;
    private javax.swing.JSpinner SCosto;
    private javax.swing.JSpinner SReporteCosto;
    private javax.swing.JTextField TBuscar;
    private javax.swing.JTable TConsultas;
    private javax.swing.JTextArea TDescripcion;
    private javax.swing.JTextField TNombre;
    private javax.swing.JToolBar Toolbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
