
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author juliann
 */
public class FTalleres extends javax.swing.JFrame {

    ConexionHR cnx;
    String tabla = "cursos";

    public FTalleres(ConexionHR cnx) {
        initComponents();

        this.cnx = cnx;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Gestión de Talleres - Casa de Cultura");

        cargarDatos();
        generarGrafica();
    }

    private void cargarDatos() {
        String talleres = "SELECT * FROM cursos ORDER BY nombre_curso";
        int resultado = cnx.entablar(talleres, TConsultas);

        if (resultado == 0) {
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los datos o la tabla está vacía.");
        }
    }

    private void limpiarCampos() {
        TNombre.setText("");
        SCosto.setValue(0);
        CBNivel.setSelectedIndex(0);
        TDescripcion.setText("");
        DCFechaInicio.setDate(null);
        DCFechaFin.setDate(null);
        TNombre.requestFocus();
    }

    private void generarGrafica() {
        String consulta = "SELECT nombre_curso, costo_semestral FROM cursos ORDER BY costo_semestral DESC";

        ArrayList<String> series = new ArrayList<>();
        series.add("Costo Semestral");

        ArrayList<ArrayList<String>> datos = cnx.consultar(consulta);

        if (datos == null || datos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay datos para graficar.");
            return;
        }

        GraficaXY grafica = new GraficaXY("Comparativa de Costos por Taller", "Taller", "Costo ($)", series, datos);

        PFondo.removeAll();
        PFondo.add(grafica.chartPanel);
        PFondo.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TConsultas = new javax.swing.JTable();
        Toolbar = new javax.swing.JToolBar();
        BNuevo = new javax.swing.JButton();
        BAgregar = new javax.swing.JButton();
        BActualizar = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BPDF = new javax.swing.JButton();
        BGrafica = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SCosto = new javax.swing.JSpinner();
        CBNivel = new javax.swing.JComboBox<>();
        DCFechaInicio = new com.toedter.calendar.JDateChooser();
        DCFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TDescripcion = new javax.swing.JTextArea();
        PFondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TALLERES");

        TConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TConsultasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TConsultas);

        Toolbar.setBackground(new java.awt.Color(0, 102, 255));
        Toolbar.setRollover(true);

        BNuevo.setText("NUEVO");
        BNuevo.setFocusable(false);
        BNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNuevo.setOpaque(true);
        BNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BNuevo.addActionListener(this::BNuevoActionPerformed);
        Toolbar.add(BNuevo);

        BAgregar.setText("AGREGAR");
        BAgregar.setFocusable(false);
        BAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAgregar.setOpaque(true);
        BAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAgregar.addActionListener(this::BAgregarActionPerformed);
        Toolbar.add(BAgregar);

        BActualizar.setText("ACTUALIZAR");
        BActualizar.setFocusable(false);
        BActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BActualizar.setOpaque(true);
        BActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BActualizar.addActionListener(this::BActualizarActionPerformed);
        Toolbar.add(BActualizar);

        BEliminar.setText("ELIMINAR");
        BEliminar.setFocusable(false);
        BEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEliminar.setOpaque(true);
        BEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEliminar.addActionListener(this::BEliminarActionPerformed);
        Toolbar.add(BEliminar);

        BPDF.setText("PDF");
        BPDF.setFocusable(false);
        BPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BPDF.setOpaque(true);
        BPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BPDF.addActionListener(this::BPDFActionPerformed);
        Toolbar.add(BPDF);

        BGrafica.setText("GRÁFICA");
        BGrafica.setFocusable(false);
        BGrafica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BGrafica.setOpaque(true);
        BGrafica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BGrafica.addActionListener(this::BGraficaActionPerformed);
        Toolbar.add(BGrafica);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Taller:"));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Costo Semanal:");

        jLabel4.setText("Nivel:");

        jLabel5.setText("Fecha de Inicio:");

        jLabel6.setText("Fecha de Finalización:");

        CBNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básico", "Intermedio", "Avanzado" }));

        jLabel7.setText("Descripción:");

        TDescripcion.setColumns(20);
        TDescripcion.setRows(5);
        jScrollPane2.setViewportView(TDescripcion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(DCFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DCFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DCFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DCFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        PFondo.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TConsultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TConsultasMousePressed
        int fila = TConsultas.getSelectedRow();

        if (fila >= 0) {
            String nombre = objToString(TConsultas.getValueAt(fila, 1));
            String descripcion = objToString(TConsultas.getValueAt(fila, 2));
            String costoStr = objToString(TConsultas.getValueAt(fila, 3));
            String nivel = objToString(TConsultas.getValueAt(fila, 4));
            String fInicioStr = objToString(TConsultas.getValueAt(fila, 5));
            String fFinStr = objToString(TConsultas.getValueAt(fila, 6));

            TNombre.setText(nombre);
            TDescripcion.setText(descripcion);
            CBNivel.setSelectedItem(nivel);

            try {
                double costo = Double.parseDouble(costoStr);
                SCosto.setValue(costo);
            } catch (NumberFormatException e) {
                System.out.println("Error al convertir costo: " + e.getMessage());
                SCosto.setValue(0.0);
            }

            DCFechaInicio.setDate(cnx.toDate(fInicioStr));
            DCFechaFin.setDate(cnx.toDate(fFinStr));
        }
    }//GEN-LAST:event_TConsultasMousePressed

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        if (DCFechaInicio.getDate() == null || DCFechaFin.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona las fechas de inicio y fin.");
            return;
        }

        String[] datos = {
            "", // ID autoincrementable
            TNombre.getText(),
            TDescripcion.getText(),
            SCosto.getValue().toString(),
            CBNivel.getSelectedItem().toString(),
            cnx.toSQL(DCFechaInicio.getDate()),
            cnx.toSQL(DCFechaFin.getDate())
        };

        if (cnx.insertar(tabla, datos) == 1) {
            JOptionPane.showMessageDialog(this, "Taller agregado exitosamente.");
            cargarDatos();
            limpiarCampos();
            generarGrafica();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el taller.");
        }
    }//GEN-LAST:event_BAgregarActionPerformed

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
        int fila = TConsultas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un taller de la tabla para actualizar.");
            return;
        }

        if (DCFechaInicio.getDate() == null || DCFechaFin.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Las fechas no pueden estar vacías.");
            return;
        }

        String id = TConsultas.getValueAt(fila, 0).toString();

        String[] datos = {
            id,
            TNombre.getText(),
            TDescripcion.getText(),
            SCosto.getValue().toString(),
            CBNivel.getSelectedItem().toString(),
            cnx.toSQL(DCFechaInicio.getDate()),
            cnx.toSQL(DCFechaFin.getDate())
        };

        if (cnx.actualizar(tabla, datos) == 1) {
            JOptionPane.showMessageDialog(this, "Taller actualizado exitosamente.");
            cargarDatos();
            limpiarCampos();
            generarGrafica();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar.");
        }
    }//GEN-LAST:event_BActualizarActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        int fila = TConsultas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un taller para eliminar.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de eliminar este taller?\nSe borrarán también sus asignaciones.",
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            String id = TConsultas.getValueAt(fila, 0).toString();
            String[] datos = {id};

            if (cnx.borrar(tabla, datos) == 1) {
                JOptionPane.showMessageDialog(this, "Taller eliminado.");
                cargarDatos();
                limpiarCampos();
                generarGrafica();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar.");
            }
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPDFActionPerformed
        String query = "SELECT nombre_curso AS Taller, nivel AS Nivel, "
                + "CONCAT('$', costo_semestral) AS Costo, "
                + "fecha_inicio AS Inicio FROM cursos ORDER BY nivel, nombre_curso";

        float[] anchos = new float[]{4f, 2f, 2f, 2f};

        int estado = cnx.crearPDF("Casa de la Cultura", "Catálogo de Talleres Disponibles", query, anchos, "ReporteTalleres");

        if (estado == 1) {
            cnx.visualizarPDF("ReporteTalleres");
        } else {
            JOptionPane.showMessageDialog(this, "Error al generar PDF.");
        }
    }//GEN-LAST:event_BPDFActionPerformed

    private void BGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGraficaActionPerformed
        generarGrafica();
    }//GEN-LAST:event_BGraficaActionPerformed

    private String objToString(Object o) {
        return o != null ? o.toString() : "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BGrafica;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BPDF;
    private javax.swing.JComboBox<String> CBNivel;
    private com.toedter.calendar.JDateChooser DCFechaFin;
    private com.toedter.calendar.JDateChooser DCFechaInicio;
    private javax.swing.JPanel PFondo;
    private javax.swing.JSpinner SCosto;
    private javax.swing.JTable TConsultas;
    private javax.swing.JTextArea TDescripcion;
    private javax.swing.JTextField TNombre;
    private javax.swing.JToolBar Toolbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
